version: '3'

services:
  #БД
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    volumes:
      - /var/opt/pgbackups:/backups
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

#бэкэнд
  app:
    depends_on:
      - postgres
    build: reg3
    container_name: 'java-app'
    volumes:
      - /var/opt/pgbackups:/backups
    ports:
      - "8011:8011"

#фронтенд
  frontend:
    depends_on:
      - app
    build: front_end
    container_name: front
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

#бэкапы
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - /var/opt/pgbackups:/backups
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:


