version : '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=Health_App'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8011:8011"

