version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    volumes:
      - /var/opt/pgbackups:/backups
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  app:
    depends_on:
      - postgres
    build: ./
    container_name: 'java-app'
    volumes:
      - /var/opt/pgbackups:/backups
    ports:
      - "8011:8011"


#  pgbackups:
#    image: prodrigestivill/postgres-backup-local
#    restart: always
#    volumes:
#      - /var/opt/pgbackups:/backups
#    links:
#      - postgres
#    depends_on:
#      - postgres
#    env_file:
#      - .env

volumes:
  postgres_data:


